In [1]:
# test bloom filter changes
from topologies import square_torus
from bloomier_filter import BloomierFilter
import numpy as np
network = square_torus(500)
children_counts = {len(c) for c in network.values()}
bloomier = BloomierFilter()
bloomier.construct(*children_counts, network)

/home/michael/spikecore/bloomier_filter.py:25: RuntimeWarning: overflow encountered in scalar multiply
  z = (z * np.uint64(0xBF58476D1CE4E5B9)) & MASK64
/home/michael/spikecore/bloomier_filter.py:27: RuntimeWarning: overflow encountered in scalar multiply
  z = (z * np.uint64(0x94D049BB133111EB)) & MASK64


KeyboardInterrupt: 

In [2]:
print(bloomier.get_neighbors(6))
print(bloomier.get_neighbors([5, 6]))

[[     7      5    506 249506]]
[[     6      4    505 249505]
 [     7      5    506 249506]]


In [3]:
from weights import WeightMatrix

weights = WeightMatrix(square_torus(10))
print(weights.get_neighbors([]))




[]


In [1]:
# test new engine
from spike_engine import SpikeEngine
from topologies import square_torus
import numpy as np

spikecore = SpikeEngine(square_torus(20), (20,20))
spikecore.set_input_neurons([1, 200])

lifetime = 50
inputspikes = np.ones((lifetime, 2))
spikecore.start_static_logfile(inputspikes, lifetime, "logtest.snnr")
print("yay")

Constructing weight matrix...
Weights constructed.


/home/michael/spikecore/bloomier_filter.py:25: RuntimeWarning: overflow encountered in scalar multiply
  z = (z * np.uint64(0xBF58476D1CE4E5B9)) & MASK64
/home/michael/spikecore/bloomier_filter.py:27: RuntimeWarning: overflow encountered in scalar multiply
  z = (z * np.uint64(0x94D049BB133111EB)) & MASK64
100%|██████████| 50/50 [00:00<00:00, 4108.04it/s]

Recording saved: logtest.snnr
yay


In [5]:
%conda install tqdm

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 25.9.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/michael/anaconda3/envs/spikecore

  added / updated specs:
    - tqdm


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tqdm-4.67.1                |  py310h2f386ee_0         134 KB
    ------------------------------------------------------------
                                           Total:         134 KB

The following NEW packages will be INSTALLED:

  tqdm               pkgs/main/linux-64::tqdm-4.67.1-py310h2f386ee_0



tqdm-4.67.1          | 134 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to