Special key pressed: Key.enter
Special key pressed: Key.enter
Special key pressed: Key.enter
Special key pressed: Key.enter
Special key pressed: Key.enter
Special key pressed: Key.enter


In [12]:
# test bloom filter changes
from topologies import square_torus
from bloomier_filter import BloomierFilter
import numpy as np
network = square_torus(200)
children_counts = {len(c) for c in network.values()}
bloomier = BloomierFilter()
bloomier.construct(*children_counts, network)

/home/michael/spikecore/bloomier_filter.py:25: RuntimeWarning:

overflow encountered in scalar multiply

/home/michael/spikecore/bloomier_filter.py:27: RuntimeWarning:

overflow encountered in scalar multiply



KeyboardInterrupt: 

In [4]:
print(bloomier.get_neighbors(6))
print(bloomier.get_neighbors([5, 6]))

[[    7     5   206 39806]]
[[    6     4   205 39805]
 [    7     5   206 39806]]


In [5]:
from weights import WeightMatrix

weights = WeightMatrix(square_torus(10))
print(weights.get_neighbors([]))




[]


In [2]:
# test new engine
from spike_engine import SpikeEngine
from topologies import square_torus
import numpy as np

spikecore = SpikeEngine(square_torus(20), (20,20))
spikecore.set_input_neurons([1, 200])

lifetime = 100
inputspikes = np.ones((lifetime, 2))
spikecore.start_static_record(inputspikes, lifetime, "logtest1.spire")
print("yay")

Constructing weight matrix...
Weights constructed.


/home/michael/spikecore/bloomier_filter.py:25: RuntimeWarning: overflow encountered in scalar multiply
  z = (z * np.uint64(0xBF58476D1CE4E5B9)) & MASK64
/home/michael/spikecore/bloomier_filter.py:27: RuntimeWarning: overflow encountered in scalar multiply
  z = (z * np.uint64(0x94D049BB133111EB)) & MASK64
100%|██████████| 100/100 [00:00<00:00, 547.50it/s]

Recording saved: logtest1.spire
yay


In [9]:
# from spike_engine import SpikeEngine
from topologies import square_torus
import numpy as np

N = 25
engine = SpikeEngine(square_torus(N), (N, N))
#engine.set_input_neurons([1e10])

engine.set_live_input_keybindings({
    "1": 501,
    "2": 101
})

engine.start_dynamic()


Constructing weight matrix...
Weights constructed.


/home/michael/spikecore/bloomier_filter.py:25: RuntimeWarning:

overflow encountered in scalar multiply

/home/michael/spikecore/bloomier_filter.py:27: RuntimeWarning:

overflow encountered in scalar multiply



AttributeError: 'SpikeEngine' object has no attribute 'input_neurons'

# 

In [ ]:
# 